apiVersion: v1
kind: PersistentVolume
metadata:
  name: lustre-local-pv-2-12
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1200Gi
  local:
    path: /lustre_fsx
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: Name
          operator: In
          values:
          - hpc-1-group-1
          - hpc-1-group-2
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem