apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-local-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1200Gi
  local:
    path: /s3_bucket
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - application
          - application-spot
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem