apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lustre-local-pvc-2-12
  namespace: lustre-app
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1200Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: lustre-local-pv-2-12